/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.ToDoLy_LukaszCzajkowski.model;

import org.junit.jupiter.api.Test;

import model.Date;

import static org.junit.Assert.assertEquals;

class DateTest {
    
    Date date;

    @Test
    void validateDateTestPositive(){
        String userUnput = "2020-12-18";
        boolean actual = Date.validateDate(userUnput);
        boolean expected = true;
        assertEquals("the value should be correct",expected, actual);
    }

    @Test
    void validateDateTestNegative(){
        String userInput = "dog";
        boolean actual = Date.validateDate(userInput);
        boolean expected = false;
        assertEquals("the value should not be valid",expected, actual);

        userInput = "2020-02-30";
        actual = Date.validateDate(userInput);
        expected = false;

        assertEquals("the value should not be valid",expected, actual);

        userInput = "2020.11.11";
        actual = Date.validateDate(userInput);
        expected = false;

        assertEquals("the value should not be valid",expected, actual);
    }
    
    @Test
    void getYearTest() {
        date = new Date("2020-11-11");
        int actual = date.getYear();
        int expected = 2020;

        assertEquals("method should return 2020",expected, actual);
    }

    @Test
    void getMonthTest() {
		date = new Date("2020-11-11");
        int actual = date.getMonth();
        int expected = 11;

        assertEquals("method should return 11",expected, actual);
	}

	@Test
    void getDayTest() {
		date = new Date("2020-11-12");
        int actual = date.getDay();
        int expected = 12;

        assertEquals("method should return 12",expected, actual);
	}
}