/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application.model;
import model.Date;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class DateTest {
    
    Date date;

    @Test
    void validateDateTestPositive(){
        String userInput = "2020-12-18";
        boolean actual = Date.validateDate(userInput);
        boolean expected = true;
        assertEquals(expected, actual);
    }

    @Test
    void validateDateTestNegative(){
        String userInput = "dog";
        boolean actual = Date.validateDate(userInput);
        boolean expected = false;
        assertEquals(expected, actual);

        userInput = "2020-02-30";
        actual = Date.validateDate(userInput);
        expected = false;

        assertEquals(expected, actual);

        userInput = "2020.11.11";
        actual = Date.validateDate(userInput);
        expected = false;

        assertEquals(expected, actual);
    }
    
    @Test
    void getYearTest() {
        date = new Date("2020-11-11");
        int actual = date.getYear();
        int expected = 2020;

        assertEquals(expected, actual);
    }

    @Test
    void getMonthTest() {
		date = new Date("2020-11-11");
        int actual = date.getMonth();
        int expected = 11;

        assertEquals(expected, actual);
	}

	@Test
    void getDayTest() {
		date = new Date("2020-11-12");
        int actual = date.getDay();
        int expected = 12;

        assertEquals(expected, actual);
	}
}